SHOW_RESULTS = "Show results"
QUIT = "Abandon hope"
TITLE = "Questionnaire"
UNANSWERED_QUESTION_ERROR_TITLE = "Missing answer"
UNANSWERED_QUESTION_ERROR_MESSAGE = "Some questions were not answered."
SELECT_QUESTIONNAIRE = "Select questionnaire"
NO_QUESTIONS_ERROR_TITLE = "No questions"
NO_QUESTIONS_ERROR_MESSAGE = "This questionnaire does not contain any questions."