SHOW_RESULTS = "Show results"
QUIT = "Abandon hope"
TITLE = "Questionnaire"
UNANSWERED_QUESTION_ERROR_TITLE = "Missing answer"
UNANSWERED_QUESTION_ERROR_MESSAGE = "Some questions were not answered."
DONT_KNOW = "I am hopeless"
